// auth actions
export const ACTION_SIGN_UP_USER = 'ACTION_SIGN_UP_USER';
export const ACTION_LOGIN_USER = 'ACTION_LOGIN_USER';
export const ACTION_LOGOUT_USER = 'ACTION_LOGOUT_USER';
export const ACTION_GET_CURRENT_USER = 'ACTION_GET_CURRENT_USER';

// user-app interaction actions
export const ACTION_ADD_MESSAGE = 'ACTION_ADD_MESSAGE';
export const ACTION_DELETE_MESSAGE = 'ACTION_DELETE_MESSAGE';
export const ACTION_EDIT_MESSAGE = 'ACTION_EDIT_MESSAGE';

export const ACTION_LIKE_MESSAGE = 'ACTION_LIKE_MESSAGE';
export const ACTION_UNLIKE_MESSAGE = 'ACTION_UNLIKE_MESSAGE';
